### ISSUE TITLE
Add swap file during provisioning

### ISSUE THREAD

**Issue by darkalor** [SPSE/lampgrant#1]
See https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors
~100MB seems to work fine

**Comment by schtanislau** [comment]
@darkalor Might be because of PHP garbage collector. Check out these references:

http://blog.ircmaxell.com/2014/12/what-about-garbage.html
http://php.net/manual/en/features.gc.php

It seems that Composer have turned of off the PHP GC in its work and amount of objects with recursive references or without references (memory leaks) are growing. This means that memory consumption also grows. First reference describes why did they disabled the GC.

**Comment by schtanislau** [comment]
#2

**Comment by schtanislau** [comment]
Merged
